import type { I18nPluginResources, PluginManifest, PluginSetup, ResourceRegistry, StorageRuntimeController, StorageCoordinatorControl } from "@keymaster/contracts";
import { RESOURCE_REGISTRY_CAPABILITY, STORAGE_RUNTIME_CONTROLLER_CAPABILITY, TOPBAR_REGISTRY_CAPABILITY, capabilityDescriptor } from "@keymaster/contracts";
import { defineRuntimeUnitDependencies } from "@keymaster/contracts";
import { StorageBucketManagerEntry } from "./ui/StorageBucketManagerPage.js";
import { StorageRpcProxy } from "./coordinator/storageRpcProxy.js";
import type { StorageRuntimeSnapshot } from "./runtime/storageRuntimeController.js";

export const STORAGE_PLATFORM_PLUGIN_ID = "storage";

const resources: I18nPluginResources = {
  namespace: "common",
  resources: {
    en: {
      "storage.settings.group": "S3 Storage", "storage.settings.provider": "Provider", "storage.settings.accountId": "Account ID", "storage.settings.endpointVariant": "Endpoint variant", "storage.settings.endpoint": "HTTPS endpoint", "storage.settings.forcePathStyle": "Force path style", "storage.settings.bucket": "Bucket", "storage.settings.region": "Region", "storage.settings.credentialsConfigured": "Credentials are configured. They are never displayed.", "storage.settings.credentialsRequired": "Enter credentials to configure storage.", "storage.settings.replaceCredentials": "Replace credentials", "storage.settings.accessKeyId": "Access key ID", "storage.settings.secretAccessKey": "Secret access key", "storage.settings.status": "Status", "storage.settings.test": "Test connection", "storage.settings.cancel": "Cancel probe", "storage.settings.clear": "Clear", "storage.settings.clearConfirm": "Clear S3 Storage configuration? Storage APIs will stop immediately.", "storage.settings.probeOk": "Provider probe succeeded.", "storage.settings.cleared": "Storage configuration cleared.", "storage.settings.failed": "Storage operation failed.", "storage.settings.locked": "Unlock the Vault to edit S3 Storage.", "storage.settings.cors": "Provider CORS must allow this app origin, GET/PUT/DELETE/POST/HEAD, Content-Type, If-Match, If-None-Match, Range and x-amz-* headers, and expose ETag, Last-Modified, Content-Range, Content-Length and x-amz-request-id.", "storage.settings.probeScope": "Connection test performs only a bounded List request; it does not prove PUT, multipart, or CORS header exposure.", "storage.settings.copyCors": "Copy CORS template", "storage.settings.corsCopied": "CORS template copied", "storage.settings.capability": "Detect write capability", "storage.settings.capabilityWarning": "This sends PUT, HEAD, DELETE and multipart requests. It may incur provider fees and retain object versions depending on lifecycle settings.", "storage.settings.capabilityUnknown": "Unknown", "storage.settings.capabilityNative": "Native atomic condition", "storage.settings.capabilityBestEffort": "Best-effort HEAD then write (not atomic)", "storage.settings.capabilityAutomatic": "Automatic", "storage.settings.capabilityManual": "Manual", "storage.settings.capabilityPut": "Conditional PUT", "storage.settings.capabilityComplete": "Multipart Complete", "storage.settings.capabilityInconclusive": "Inconclusive; previous state retained", "storage.settings.capabilityBusy": "Capability detection in progress", "storage.settings.capabilityDone": "Write capability detection completed.", "storage.settings.capabilityCleanupWarning": "Detection completed, but cleanup reported a warning."
    },
    "zh-CN": {
      "storage.settings.group": "S3 存储", "storage.settings.provider": "Provider", "storage.settings.accountId": "Account ID", "storage.settings.endpointVariant": "Endpoint 变体", "storage.settings.endpoint": "HTTPS Endpoint", "storage.settings.forcePathStyle": "强制 Path Style", "storage.settings.bucket": "Bucket", "storage.settings.region": "Region", "storage.settings.credentialsConfigured": "凭据已配置，不会回显。", "storage.settings.credentialsRequired": "请输入凭据以配置存储。", "storage.settings.replaceCredentials": "替换凭据", "storage.settings.accessKeyId": "Access Key ID", "storage.settings.secretAccessKey": "Secret Access Key", "storage.settings.status": "状态", "storage.settings.test": "测试连接", "storage.settings.cancel": "取消 Probe", "storage.settings.clear": "清除", "storage.settings.clearConfirm": "清除 S3 存储配置？Storage API 将立即停止。", "storage.settings.probeOk": "Provider Probe 成功。", "storage.settings.cleared": "Storage 配置已清除。", "storage.settings.failed": "Storage 操作失败。", "storage.settings.locked": "请先解锁 Vault 才能编辑 S3 存储。", "storage.settings.cors": "Provider CORS 必须允许当前 App Origin、GET/PUT/DELETE/POST/HEAD，以及 Content-Type、If-Match、If-None-Match、Range、x-amz-* 请求头，并暴露 ETag、Last-Modified、Content-Range、Content-Length、x-amz-request-id。", "storage.settings.probeScope": "连接测试只执行有界 List 请求，不能证明 PUT、multipart 或 CORS 响应头暴露配置正确。", "storage.settings.copyCors": "复制 CORS 模板", "storage.settings.corsCopied": "CORS 模板已复制", "storage.settings.capability": "检测写入能力", "storage.settings.capabilityWarning": "此操作会发送 PUT、HEAD、DELETE 和 multipart 请求，可能产生 Provider 费用；根据生命周期设置，历史版本可能保留。", "storage.settings.capabilityUnknown": "未知", "storage.settings.capabilityNative": "原生原子条件写入", "storage.settings.capabilityBestEffort": "Best-effort HEAD 后写入（非原子）", "storage.settings.capabilityAutomatic": "自动", "storage.settings.capabilityManual": "手动", "storage.settings.capabilityPut": "条件 PUT", "storage.settings.capabilityComplete": "Multipart Complete", "storage.settings.capabilityInconclusive": "无法确定；保留之前状态", "storage.settings.capabilityBusy": "写入能力检测进行中", "storage.settings.capabilityDone": "写入能力检测完成。", "storage.settings.capabilityCleanupWarning": "检测完成，但清理时出现警告。"
    }
  }
};

(resources.resources.en as Record<string, string>)["storage.settings.capabilityScope"] = "This checks the active configuration after automatic saving has completed.";
(resources.resources["zh-CN"] as Record<string, string>)["storage.settings.capabilityScope"] = "此检测会在自动保存和激活完成后，使用当前生效的配置。";

Object.assign(resources.resources.en as Record<string, string>, {
  "storage.settings.backend": "Storage backend",
  "storage.settings.notActivated": "Not activated",
  "storage.settings.providerTitle": "Provider",
  "storage.settings.providerDescription": "Choose the object storage service for this Bucket.",
  "storage.settings.parametersTitle": "Parameters",
  "storage.settings.parametersDescription": "Connect directly to the Bucket root. App data is isolated automatically.",
  "storage.settings.connectionTitle": "Connection",
  "storage.settings.connectionDescription": "Choose a provider and enter its bucket location.",
  "storage.settings.credentialsTitle": "Credentials",
  "storage.settings.profilePassword": "Storage Profile password",
  "storage.settings.profilePasswordRequired": "Enter a Storage Profile password of at least 8 characters.",
  "storage.settings.unlockProfile": "Unlock Storage Profile",
  "storage.settings.selectOpfs": "Use local OPFS",
  "storage.settings.importProfile": "Import Storage Profile",
  "storage.settings.profileUnlocked": "Storage Profile unlocked.",
  "storage.settings.credentialsSealed": "Stored in the encrypted Storage Profile and never displayed.",
  "storage.settings.browserAccessTitle": "Browser access",
  "storage.settings.r2Cors": "R2 must allow this exact app origin before browser requests can reach the bucket.",
  "storage.settings.corsOriginExact": "The scheme, hostname and port must match exactly.",
  "storage.settings.showCors": "Show CORS policy",
  "storage.settings.r2CorsDocs": "Cloudflare R2 CORS guide",
  "storage.settings.endpointPreview": "S3 endpoint",
  "storage.settings.verificationTitle": "Verification",
  "storage.settings.capabilityRequiresReady": "Complete the required parameters and wait for automatic activation before detecting write capability.",
  "storage.settings.networkOrCors": "The browser request was blocked by network or CORS. Apply this page's CORS template to the Bucket and make sure AllowedOrigins contains {{origin}} exactly, then retry.",
  "storage.settings.authenticationFailed": "Storage authentication failed. Check that you entered an R2 S3 access key ID and secret access key, not an account API token.",
  "storage.settings.forbidden": "The storage provider denied this operation. Check the key's bucket permissions.",
  "storage.settings.autoSaveIdle": "Changes save automatically",
  "storage.settings.autoSaveWaiting": "Waiting to save…",
  "storage.settings.autoSaveIncomplete": "Complete the required parameters to save automatically.",
  "storage.settings.autoSaveSaving": "Saving and activating…",
  "storage.settings.autoSaveSaved": "Saved and active",
  "storage.settings.autoSaveError": "Not saved — fix the error and retry",
  "storage.settings.statusReady": "Ready",
  "storage.settings.statusUnconfigured": "Not configured",
      "storage.settings.statusDegraded": "Needs attention",
      "storage.settings.statusReconfiguring": "Reconfiguring",
      "storage.bucketManager.topbar": "Storage buckets",
      "storage.bucketManager.title": "Storage buckets",
      "storage.bucketManager.description": "Buckets are the outermost system boundary. Each bucket owns its password, connection configuration, and Keys.",
      "storage.bucketManager.listTitle": "Saved buckets",
      "storage.bucketManager.bucketCount": "buckets",
      "storage.bucketManager.empty": "No buckets yet. Create one to save an encrypted connection record locally.",
      "storage.bucketManager.selected": "Current",
      "storage.bucketManager.newTitle": "Add a bucket",
      "storage.bucketManager.label": "Bucket name",
      "storage.bucketManager.backend": "Backend",
      "storage.bucketManager.password": "Bucket password",
      "storage.bucketManager.passwordConfirm": "Confirm bucket password",
      "storage.bucketManager.passwordNote": "The bucket password exists only for the current test and save operation. It is not written to the catalog, logs, or long-lived Coordinator state. Cold export reads only the committed snapshot.",
      "storage.bucketManager.test": "Test",
      "storage.bucketManager.save": "Save bucket",
      "storage.bucketManager.tested": "Test passed. Save is enabled until the draft changes.",
      "storage.bucketManager.saved": "Bucket saved to the local catalog.",
      "storage.bucketManager.export": "Export",
      "storage.bucketManager.rename": "Rename",
      "storage.bucketManager.edit": "Edit config",
      "storage.bucketManager.editTitle": "Edit bucket connection",
      "storage.bucketManager.editPassword": "Enter the current bucket password to edit the connection",
      "storage.bucketManager.editLoaded": "Configuration loaded. Test it again after editing, then save.",
      "storage.bucketManager.currentPassword": "Current bucket password (verified)",
      "storage.bucketManager.saveEdit": "Save config",
      "storage.bucketManager.remove": "Remove connection",
      "storage.bucketManager.renamePrompt": "Enter a new bucket name",
      "storage.bucketManager.renamed": "Bucket name updated.",
      "storage.bucketManager.destroy": "Destroy local data",
      "storage.bucketManager.destroyVisible": "Delete visible objects",
      "storage.bucketManager.destroyConfirm": "Destroy all local data in {{label}}? This cannot be undone and also removes the local connection.",
      "storage.bucketManager.destroyVisibleConfirm": "Delete the currently visible S3 objects in {{label}}? Object versions, delete markers, and incomplete multipart uploads may remain; the local connection will also be removed.",
      "storage.bucketManager.destroyPassword": "Enter the S3 bucket password to delete its currently visible objects",
      "storage.bucketManager.destroyed": "Local bucket data destroyed and connection removed ({{count}} objects).",
      "storage.bucketManager.destroyedVisible": "Currently visible S3 objects deleted and connection removed ({{count}} objects); historical data may remain.",
      "storage.bucketManager.removed": "Connection removed; bucket data was kept.",
      "storage.bucketManager.err.rename": "Failed to rename the bucket",
      "storage.bucketManager.err.remove": "Failed to remove the bucket connection",
      "storage.bucketManager.err.currentRemove": "The current bucket is in use; switch buckets before removing it.",
      "storage.bucketManager.err.currentDestroy": "The current bucket is in use; switch buckets before destroying its data.",
      "storage.bucketManager.err.destroy": "Failed to destroy bucket data; deletion stopped.",
      "storage.bucketManager.err.passwordRequired": "The bucket password is required to destroy S3 data.",
      "storage.bucketManager.keySwitchTitle": "Switch Key",
      "storage.bucketManager.bucketPassword": "Bucket password",
      "storage.bucketManager.vaultPassword": "Vault password",
      "storage.bucketManager.keySwitchSubmit": "Switch with password",
      "storage.bucketManager.err.keySwitch": "Failed to switch Key",
      "storage.bucketManager.unnamedKey": "Unnamed Key",
      "storage.bucketManager.currentKey": "Current",
      "storage.bucketManager.removeConfirm": "Remove only the local connection entry? Bucket data will not be destroyed.",
      "storage.bucketManager.err.exportSession": "Unlock and enter the S3 bucket session before exporting its committed snapshot.",
      "storage.bucketManager.exported": "The committed Hold configuration snapshot was exported.",
      "storage.bucketManager.err.label": "Enter a bucket name",
      "storage.bucketManager.err.password": "Bucket password must contain at least 8 characters",
      "storage.bucketManager.err.passwordMismatch": "Bucket passwords do not match",
      "storage.bucketManager.err.s3Required": "Enter the S3 endpoint, region, bucket, and access credentials",
      "storage.bucketManager.err.conditionalWrites": "The bucket does not support the required atomic conditional writes",
      "storage.bucketManager.err.test": "Bucket test failed. Check the configuration and try again.",
      "storage.bucketManager.err.testFirst": "Test the current draft first. Changing a parameter requires another test.",
      "storage.bucketManager.err.save": "Save failed. Keep the draft and try again.",
      "storage.bucketManager.unlockTitle": "Unlock current bucket",
      "storage.bucketManager.unlockDescription": "A cold start shows only bucket metadata. Enter the temporary bucket password to read Keys.",
      "storage.bucketManager.unlock": "Unlock bucket",
      "storage.bucketManager.unlocked": "Bucket unlocked; runtime recovery is in progress.",
      "storage.bucketManager.err.unlock": "The bucket password is invalid or the bucket could not be read.",
      "storage.bucketManager.reloadHint": "The new bucket is now selected. Reload to enter the new bucket session.",
      "storage.bucketManager.reload": "Reload",
      "storage.bucketManager.treeTitle": "Buckets / Keys",
      "storage.bucketManager.manage": "Manage",
      "storage.bucketManager.noKeys": "No Keys",
      "storage.bucketManager.readKeys": "Enter password to read Keys",
      "storage.bucketManager.switchPasswordPrompt": "Enter the bucket password for {{label}}",
      "storage.bucketManager.err.switch": "Bucket switch failed",
      "storage.bucketManager.legacyTitle": "Legacy storage detected",
      "storage.bucketManager.legacyOpfs": "This is legacy single-bucket OPFS data. The new flow will not silently map it to Local or delete the original data.",
      "storage.bucketManager.legacyProfile": "This is a legacy independent Storage Profile. It uses a different password and storage model from the new bucket catalog.",
      "storage.bucketManager.legacyProfileHint": "Export the encrypted Profile first. Its old password is used only by the legacy unlock flow; export does not decrypt credentials.",
      "storage.bucketManager.legacyExportProfile": "Export legacy Profile",
      "storage.bucketManager.legacyProfileExported": "The legacy Storage Profile was exported; the original record was kept and not migrated.",
      "storage.bucketManager.legacyKeysTitle": "Legacy KeyHold backups",
      "storage.bucketManager.legacyKeysHint": "Export each encrypted KeyHold file, then import them one by one from Key management after creating a new bucket.",
      "storage.bucketManager.legacyExportKey": "Export KeyHold",
      "storage.bucketManager.legacyKeyExported": "The legacy KeyHold backup was exported; the original OPFS data was kept.",
      "storage.bucketManager.legacyKeysEmpty": "No legacy Keys were read yet; confirm that the legacy OPFS session has started.",
      "storage.bucketManager.openKeyManagement": "Open Key management",
      "storage.bucketManager.legacyMigrationNote": "Migration is explicit and reversible: export and verify old files, then create a new Local/S3 bucket. Do not clean up legacy OPFS or Profile data until the new bucket is confirmed usable.",
      "storage.bucketManager.import": "Import a bucket",
      "storage.bucketManager.importLabel": "Enter a name for the imported bucket",
      "storage.bucketManager.importPassword": "Enter the Hold file password",
      "storage.bucketManager.imported": "The Hold configuration was verified and imported. Reload to enter this bucket.",
      "storage.bucketManager.changePassword": "Change password",
      "storage.bucketManager.oldPassword": "Enter the current bucket password",
      "storage.bucketManager.newPassword": "Enter a new bucket password (at least 8 characters)",
      "storage.bucketManager.newPasswordConfirm": "Enter the new bucket password again",
      "storage.bucketManager.passwordChanged": "The bucket password and all Key snapshots were updated. Reload and use the new password.",
      "storage.bucketManager.switch": "Switch",
      "storage.bucketManager.switchPassword": "Enter this bucket's password",
      "storage.bucketManager.switchedUnlocked": "Switched buckets and restored the current Key session.",
      "storage.bucketManager.switched": "Switched buckets. Enter the bucket password below to unlock the Key session.",
      "storage.bucketManager.more": "More bucket actions",
      "storage.bucketManager.switchKey": "Switch",
      "storage.bucketManager.switchToReadKeys": "Switch to this bucket to read its Keys",
      "storage.bucketManager.err.catalog": "The local bucket catalog is unavailable. Restore browser local storage and try again.",
      "storage.bucketManager.err.edit": "Failed to read the bucket configuration. Check the password.",
      "storage.bucketManager.err.export": "Export failed. Check the bucket connection or current session.",
      "storage.bucketManager.err.import": "Import failed. Check the file and password.",
      "storage.bucketManager.err.passwordChange": "Failed to change the bucket password. The old password is still valid.",
      "storage.bucketManager.err.switchUnavailable": "This Coordinator cannot switch buckets safely. Reload and try again.",
      "storage.bucketFields.type": "Bucket type (storage backend)",
      "storage.bucketFields.local": "Local (browser storage)",
      "storage.bucketFields.s3": "S3 (S3-compatible object storage)",
      "storage.bucketFields.label": "Bucket name (local display name)",
      "storage.bucketFields.labelPlaceholder": "For example: Workspace",
      "storage.bucketFields.s3Mode": "Configuration mode (S3 connection template)",
      "storage.bucketFields.awsS3": "AWS S3",
      "storage.bucketFields.cloudflareR2": "Cloudflare R2",
      "storage.bucketFields.s3Compatible": "Other S3-compatible service",
      "storage.bucketFields.endpoint": "Endpoint (HTTPS service URL)",
      "storage.bucketFields.region": "Region (storage/signing region)",
      "storage.bucketFields.accountId": "Account ID (Cloudflare account ID)",
      "storage.bucketFields.endpointVariant": "Endpoint variant (R2 endpoint type)",
      "storage.bucketFields.r2Default": "Default",
      "storage.bucketFields.r2Eu": "EU",
      "storage.bucketFields.r2Us": "US",
      "storage.bucketFields.r2Fedramp": "FedRAMP",
      "storage.bucketFields.awsEndpointNote": "Endpoint (generated automatically)",
      "storage.bucketFields.r2EndpointNote": "Endpoint (generated automatically)",
      "storage.bucketFields.virtualHostNote": "Requests use virtual-hosted style; Force Path Style is fixed to false.",
      "storage.bucketFields.bucket": "Bucket (physical bucket name)",
      "storage.bucketFields.accessKey": "Access Key ID (access identity)",
      "storage.bucketFields.secretKey": "Secret Access Key (access secret)",
      "storage.bucketFields.sessionToken": "Session Token (optional temporary token)",
      "storage.bucketFields.prefix": "Prefix (optional object path prefix)",
      "storage.bucketFields.prefixPlaceholder": "For example: team-a/",
      "storage.bucketFields.forcePathStyle": "Force Path Style (path-style requests)",
      "storage.bucketFields.localNote": "A Local bucket stays in this browser and is best for one device. It is not synchronized to other devices.",
      "storage.bucketFields.currentPassword": "Current bucket password (verified)",
      "storage.bucketFields.password": "Password (at least 8 characters)",
      "storage.bucketFields.passwordConfirm": "Confirm password",
      "storage.bucketManager.err.s3-mode-invalid": "Choose AWS S3, Cloudflare R2, or another S3-compatible service.",
      "storage.bucketManager.err.aws-region-required": "Enter Region (AWS region).",
      "storage.bucketManager.err.aws-region-invalid": "The AWS Region is unsupported or invalid. Supported partitions are commercial AWS, China, and GovCloud.",
      "storage.bucketManager.err.s3-region-required": "Enter Region (S3 signing region).",
      "storage.bucketManager.err.r2-account-required": "Enter Account ID (Cloudflare account ID).",
      "storage.bucketManager.err.r2-account-invalid": "Account ID must be a 32-character hexadecimal string.",
      "storage.bucketManager.err.r2-endpoint-variant-invalid": "Endpoint variant must be Default, EU, US, or FedRAMP.",
      "storage.bucketManager.err.s3-endpoint-required": "Enter Endpoint (HTTPS service URL).",
      "storage.bucketManager.err.s3-endpoint-invalid": "Endpoint must be an absolute HTTPS URL without credentials, query, or fragment.",
      "storage.bucketManager.err.s3-bucket-required": "Enter Bucket (physical bucket name).",
      "storage.bucketManager.err.s3-bucket-invalid": "Bucket must be a valid 3–63 character lowercase S3 bucket name.",
      "storage.bucketManager.err.s3-credentials-required": "Enter Access Key ID and Secret Access Key.",
      "storage.bucketManager.err.s3-session-token-invalid": "Session Token cannot contain control characters.",
      "storage.bucketManager.err.s3-prefix-invalid": "Prefix must be a safe relative object path without . or .. segments.",
      "storage.bucketManager.err.legacyExport": "Legacy storage export failed"
});

Object.assign(resources.resources["zh-CN"] as Record<string, string>, {
  "storage.settings.backend": "存储后端",
  "storage.settings.notActivated": "尚未激活",
  "storage.settings.providerTitle": "Provider",
  "storage.settings.providerDescription": "选择这个 Bucket 使用的对象存储服务。",
  "storage.settings.parametersTitle": "各项参数",
  "storage.settings.parametersDescription": "直接连接 Bucket 根目录，系统会自动隔离每个 App 的数据。",
  "storage.settings.connectionTitle": "连接配置",
  "storage.settings.connectionDescription": "选择存储服务并填写 Bucket 位置。",
  "storage.settings.credentialsTitle": "访问凭据",
  "storage.settings.profilePassword": "Storage Profile 独立密码",
  "storage.settings.profilePasswordRequired": "请输入至少 8 位的 Storage Profile 独立密码。",
  "storage.settings.unlockProfile": "解锁 Storage Profile",
  "storage.settings.selectOpfs": "选择本机 OPFS",
  "storage.settings.importProfile": "导入 Storage Profile",
  "storage.settings.profileUnlocked": "Storage Profile 已解锁。",
  "storage.settings.credentialsSealed": "已加密保存在 Storage Profile 中，不会回显。",
  "storage.settings.browserAccessTitle": "浏览器访问",
  "storage.settings.r2Cors": "浏览器访问 R2 前，Bucket 必须允许当前应用的精确 Origin。",
  "storage.settings.corsOriginExact": "协议、主机名和端口必须完全一致。",
  "storage.settings.showCors": "查看 CORS 配置",
  "storage.settings.r2CorsDocs": "Cloudflare R2 CORS 文档",
  "storage.settings.endpointPreview": "S3 Endpoint",
  "storage.settings.verificationTitle": "连接验证",
  "storage.settings.capabilityRequiresReady": "请填写完整的必填参数，并等待自动激活完成后再检测写入能力。",
  "storage.settings.networkOrCors": "浏览器请求被网络或 CORS 拦截。请将本页 CORS 模板配置到 Bucket，并确认 AllowedOrigins 精确包含 {{origin}} 后重试。",
  "storage.settings.authenticationFailed": "存储身份验证失败。请确认填写的是 R2 的 S3 Access Key ID 和 Secret Access Key，而不是账户 API Token。",
  "storage.settings.forbidden": "存储服务拒绝了此操作，请检查该密钥的 Bucket 权限。",
  "storage.settings.autoSaveIdle": "修改会自动保存",
  "storage.settings.autoSaveWaiting": "等待自动保存…",
  "storage.settings.autoSaveIncomplete": "填写完整的必填参数后将自动保存。",
  "storage.settings.autoSaveSaving": "正在保存并激活…",
  "storage.settings.autoSaveSaved": "已保存并激活",
  "storage.settings.autoSaveError": "尚未保存，请修正错误后重试",
  "storage.settings.statusReady": "已就绪",
  "storage.settings.statusUnconfigured": "未配置",
      "storage.settings.statusDegraded": "需要处理",
      "storage.settings.statusReconfiguring": "正在重新配置",
      "storage.bucketManager.topbar": "存储桶",
      "storage.bucketManager.title": "存储桶",
      "storage.bucketManager.description": "桶是系统最外层边界。每个桶拥有自己的密码、连接配置和 Keys。",
      "storage.bucketManager.listTitle": "已保存的桶",
      "storage.bucketManager.bucketCount": "个桶",
      "storage.bucketManager.empty": "还没有存储桶。创建后，连接密文只保存在本机目录中。",
      "storage.bucketManager.selected": "当前",
      "storage.bucketManager.newTitle": "添加存储桶",
      "storage.bucketManager.label": "桶名称",
      "storage.bucketManager.backend": "后端",
      "storage.bucketManager.password": "桶密码",
      "storage.bucketManager.passwordConfirm": "确认桶密码",
      "storage.bucketManager.passwordNote": "桶密码只用于当前测试和保存操作；不会写入目录、日志或长期 Coordinator 状态。冷导出只读取已提交快照。",
      "storage.bucketManager.test": "测试",
      "storage.bucketManager.save": "保存桶",
      "storage.bucketManager.tested": "测试成功。草稿未改变时可以保存。",
      "storage.bucketManager.saved": "存储桶已保存到本机目录。",
      "storage.bucketManager.export": "导出",
      "storage.bucketManager.rename": "改名",
      "storage.bucketManager.edit": "编辑配置",
      "storage.bucketManager.editTitle": "编辑桶连接配置",
      "storage.bucketManager.editPassword": "输入当前桶密码以编辑连接配置",
      "storage.bucketManager.editLoaded": "配置已读取。修改后请重新测试，再保存。",
      "storage.bucketManager.currentPassword": "当前桶密码（已验证）",
      "storage.bucketManager.saveEdit": "保存配置",
      "storage.bucketManager.remove": "移除连接",
      "storage.bucketManager.renamePrompt": "输入新的桶名称",
      "storage.bucketManager.renamed": "桶名称已更新。",
      "storage.bucketManager.destroy": "销毁本地数据",
      "storage.bucketManager.destroyVisible": "删除可见对象",
      "storage.bucketManager.destroyConfirm": "确认销毁“{{label}}”中的全部本地桶数据？此操作不可恢复，并会同时移除本机连接项。",
      "storage.bucketManager.destroyVisibleConfirm": "确认删除“{{label}}”中当前可见的 S3 对象？对象版本、Delete Marker 和未完成 multipart 可能保留；同时移除本机连接项。",
      "storage.bucketManager.destroyPassword": "输入该 S3 桶密码以删除当前可见对象",
      "storage.bucketManager.destroyed": "已销毁本地桶数据并移除连接项（{{count}} 个对象）。",
      "storage.bucketManager.destroyedVisible": "已删除当前可见 S3 对象并移除连接项（{{count}} 个）；历史数据可能仍保留。",
      "storage.bucketManager.removed": "连接项已移除；桶内数据未删除。",
      "storage.bucketManager.err.rename": "修改桶名称失败",
      "storage.bucketManager.err.remove": "删除桶连接项失败",
      "storage.bucketManager.err.currentRemove": "当前桶正在使用，不能直接移除；请先切换到其他桶。",
      "storage.bucketManager.err.currentDestroy": "当前桶正在使用，不能销毁数据；请先切换到其他桶。",
      "storage.bucketManager.err.destroy": "销毁桶数据失败；已停止删除。",
      "storage.bucketManager.err.passwordRequired": "销毁 S3 数据需要桶密码。",
      "storage.bucketManager.keySwitchTitle": "切换 Key",
      "storage.bucketManager.bucketPassword": "桶密码",
      "storage.bucketManager.vaultPassword": "Vault 密码",
      "storage.bucketManager.keySwitchSubmit": "使用密码切换",
      "storage.bucketManager.err.keySwitch": "切换 Key 失败",
      "storage.bucketManager.unnamedKey": "未命名 Key",
      "storage.bucketManager.currentKey": "当前",
      "storage.bucketManager.removeConfirm": "只移除本机目录中的连接项？桶内数据不会被销毁。",
      "storage.bucketManager.err.exportSession": "S3 桶需要先解锁并进入当前会话后才能冷导出",
      "storage.bucketManager.exported": "已导出当前已提交的完整 Hold 配置快照。",
      "storage.bucketManager.err.label": "请输入桶名称",
      "storage.bucketManager.err.password": "桶密码至少 8 位",
      "storage.bucketManager.err.passwordMismatch": "两次桶密码不一致",
      "storage.bucketManager.err.s3Required": "请填写 S3 Endpoint、区域、Bucket 和访问凭据",
      "storage.bucketManager.err.conditionalWrites": "桶不支持必须的原子条件写入",
      "storage.bucketManager.err.test": "桶测试失败，请检查配置后重试",
      "storage.bucketManager.err.testFirst": "请先测试当前草稿；修改参数后需要重新测试",
      "storage.bucketManager.err.save": "保存失败，请保留草稿并重试",
      "storage.bucketManager.unlockTitle": "输入当前桶密码",
      "storage.bucketManager.unlockDescription": "冷启动只显示桶目录；读取 Keys 前需要临时解锁当前桶。",
      "storage.bucketManager.unlock": "解锁桶",
      "storage.bucketManager.unlocked": "桶已解锁，正在恢复运行时。",
      "storage.bucketManager.err.unlock": "桶密码错误或桶读取失败",
      "storage.bucketManager.reloadHint": "新桶已成为当前桶；重新加载后会进入新的桶会话。",
      "storage.bucketManager.reload": "重新加载",
      "storage.bucketManager.treeTitle": "桶 / Keys",
      "storage.bucketManager.manage": "管理",
      "storage.bucketManager.noKeys": "暂无 Keys",
      "storage.bucketManager.readKeys": "输入密码读取 Keys",
      "storage.bucketManager.switchPasswordPrompt": "请输入“{{label}}”的桶密码",
      "storage.bucketManager.err.switch": "切换桶失败",
      "storage.bucketManager.legacyTitle": "检测到旧版存储",
      "storage.bucketManager.legacyOpfs": "这是旧版 OPFS 单桶数据。新版不会把它静默映射成 Local，也不会删除原数据。",
      "storage.bucketManager.legacyProfile": "这是旧版独立 Storage Profile。它与新版桶目录、桶密码模型不同，不能直接当作新版桶。",
      "storage.bucketManager.legacyProfileHint": "先导出加密 Profile 文件，原密码仍只用于旧版解锁；导出不会解密凭据。",
      "storage.bucketManager.legacyExportProfile": "导出旧 Profile",
      "storage.bucketManager.legacyProfileExported": "旧版 Storage Profile 已导出；原记录仍保留，未自动迁移。",
      "storage.bucketManager.legacyKeysTitle": "旧版 KeyHold 备份",
      "storage.bucketManager.legacyKeysHint": "逐把导出加密 KeyHold 文件，再创建新版桶后从 Key 管理中逐项导入。",
      "storage.bucketManager.legacyExportKey": "导出 KeyHold",
      "storage.bucketManager.legacyKeyExported": "旧版 KeyHold 备份已导出；原 OPFS 数据仍保留。",
      "storage.bucketManager.legacyKeysEmpty": "暂未读取到旧 Key；请确认旧 OPFS 会话已启动。",
      "storage.bucketManager.openKeyManagement": "打开 Key 管理",
      "storage.bucketManager.legacyMigrationNote": "迁移是显式、逐步且可回退的：先导出并验证旧文件，再创建新版 Local/S3 桶；在确认新桶可用前，不要清理旧 OPFS 或旧 Profile。",
      "storage.bucketManager.import": "导入桶",
      "storage.bucketManager.importLabel": "输入导入桶名称",
      "storage.bucketManager.importPassword": "输入 Hold 文件密码",
      "storage.bucketManager.imported": "Hold 配置已验证并导入；重新加载后进入该桶。",
      "storage.bucketManager.changePassword": "修改密码",
      "storage.bucketManager.oldPassword": "输入当前桶密码",
      "storage.bucketManager.newPassword": "输入新的桶密码（至少 8 位）",
      "storage.bucketManager.newPasswordConfirm": "再次输入新的桶密码",
      "storage.bucketManager.passwordChanged": "桶密码和全部 Key 快照已更新；重新加载后使用新密码。",
      "storage.bucketManager.switch": "切换",
      "storage.bucketManager.switchPassword": "输入该桶的密码",
      "storage.bucketManager.switchedUnlocked": "已切换桶，当前 Key 会话已恢复。",
      "storage.bucketManager.switched": "已切换桶；请在下方输入桶密码解锁 Key 会话。",
      "storage.bucketManager.more": "更多桶操作",
      "storage.bucketManager.switchKey": "切换",
      "storage.bucketManager.switchToReadKeys": "切换到此桶后读取 Keys",
      "storage.bucketManager.err.catalog": "本机存储桶目录不可用，请先恢复浏览器本地存储后重试。",
      "storage.bucketManager.err.edit": "读取桶配置失败，请检查密码。",
      "storage.bucketManager.err.export": "导出失败，请检查桶连接或当前会话。",
      "storage.bucketManager.err.import": "导入失败，请检查文件和密码。",
      "storage.bucketManager.err.passwordChange": "桶密码修改失败，旧密码仍然有效。",
      "storage.bucketManager.err.switchUnavailable": "当前 Coordinator 不支持安全切桶，请刷新页面后重试。",
      "storage.bucketFields.type": "桶类型（存储后端）",
      "storage.bucketFields.local": "Local（浏览器本地存储）",
      "storage.bucketFields.s3": "S3（兼容 S3 的对象存储）",
      "storage.bucketFields.label": "桶名称（本机显示名称）",
      "storage.bucketFields.labelPlaceholder": "例如：工作空间",
      "storage.bucketFields.s3Mode": "配置方式（S3 连接模板）",
      "storage.bucketFields.awsS3": "AWS S3（亚马逊对象存储）",
      "storage.bucketFields.cloudflareR2": "Cloudflare R2（Cloudflare 对象存储）",
      "storage.bucketFields.s3Compatible": "普通 S3-compatible（其他兼容服务）",
      "storage.bucketFields.endpoint": "Endpoint（HTTPS 服务地址）",
      "storage.bucketFields.region": "Region（存储区域/签名区域）",
      "storage.bucketFields.accountId": "Account ID（Cloudflare 账户 ID）",
      "storage.bucketFields.endpointVariant": "Endpoint Variant（R2 端点类型）",
      "storage.bucketFields.r2Default": "Default（默认）",
      "storage.bucketFields.r2Eu": "EU（欧洲）",
      "storage.bucketFields.r2Us": "US（美国）",
      "storage.bucketFields.r2Fedramp": "FedRAMP（合规端点）",
      "storage.bucketFields.awsEndpointNote": "Endpoint（自动生成）",
      "storage.bucketFields.r2EndpointNote": "Endpoint（自动生成）",
      "storage.bucketFields.virtualHostNote": "请求固定使用虚拟主机风格；Force Path Style 固定为 false。",
      "storage.bucketFields.bucket": "Bucket（物理桶名称）",
      "storage.bucketFields.accessKey": "Access Key ID（访问身份）",
      "storage.bucketFields.secretKey": "Secret Access Key（访问密钥）",
      "storage.bucketFields.sessionToken": "Session Token（临时会话令牌，可选）",
      "storage.bucketFields.prefix": "Prefix（对象路径前缀，可选）",
      "storage.bucketFields.prefixPlaceholder": "例如：team-a/",
      "storage.bucketFields.forcePathStyle": "Force Path Style（强制路径风格请求）",
      "storage.bucketFields.localNote": "Local 桶保存在当前浏览器中，适合单设备使用；不会同步到其他设备。",
      "storage.bucketFields.currentPassword": "当前桶密码（已验证）",
      "storage.bucketFields.password": "密码（至少 8 位）",
      "storage.bucketFields.passwordConfirm": "确认密码",
      "storage.bucketManager.err.s3-mode-invalid": "请选择 AWS S3、Cloudflare R2 或普通 S3-compatible 配置方式。",
      "storage.bucketManager.err.aws-region-required": "请填写 Region（AWS 区域）。",
      "storage.bucketManager.err.aws-region-invalid": "AWS Region 不属于支持的分区或格式不正确；支持商业区、中国区和 GovCloud。",
      "storage.bucketManager.err.s3-region-required": "请填写 Region（S3 签名区域）。",
      "storage.bucketManager.err.r2-account-required": "请填写 Account ID（Cloudflare 账户 ID）。",
      "storage.bucketManager.err.r2-account-invalid": "Account ID 必须是 32 位十六进制字符串。",
      "storage.bucketManager.err.r2-endpoint-variant-invalid": "Endpoint Variant 只能选择 Default、EU、US 或 FedRAMP。",
      "storage.bucketManager.err.s3-endpoint-required": "请填写 Endpoint（HTTPS 服务地址）。",
      "storage.bucketManager.err.s3-endpoint-invalid": "Endpoint 必须是无凭据、无 query、无 fragment 的绝对 HTTPS 地址。",
      "storage.bucketManager.err.s3-bucket-required": "请填写 Bucket（物理桶名称）。",
      "storage.bucketManager.err.s3-bucket-invalid": "Bucket 必须是合法的 3～63 位小写 S3 桶名称。",
      "storage.bucketManager.err.s3-credentials-required": "请填写 Access Key ID（访问身份）和 Secret Access Key（访问密钥）。",
      "storage.bucketManager.err.s3-session-token-invalid": "Session Token 不能包含控制字符。",
      "storage.bucketManager.err.s3-prefix-invalid": "Prefix 必须是安全的相对对象路径，不能包含 . 或 .. 段。",
      "storage.bucketManager.err.legacyExport": "旧版存储导出失败"
});

const storagePlatformPluginDefinition = {
  id: STORAGE_PLATFORM_PLUGIN_ID,
  name: "Storage",
  description: "隔离的 Connect S3-compatible object storage capability.",
  kind: "platform", startup: "required", bootstrapStage: "storage-onboarding", defaultEnabled: true, canDisable: false, displayGroup: "platform",
  units: [{
    id: "storage.window",
    runtime: "window-main",
    scopeKind: "storage",
    provides: [capabilityDescriptor(STORAGE_RUNTIME_CONTROLLER_CAPABILITY)],
    dependencies: defineRuntimeUnitDependencies([
      { capability: TOPBAR_REGISTRY_CAPABILITY, sourceRuntime: "window-main" },
    ]),
  }, {
    id: "storage.coordinator-worker",
    runtime: "shared-worker",
    scopeKind: "storage",
  }],
  i18n: resources,
  async setup(ctx) {
    const coordinator = ctx.coordinator as StorageCoordinatorControl | undefined;
    if (!coordinator) throw new Error("Storage Coordinator control is unavailable");
    const service = new StorageRpcProxy(coordinator);
    ctx.provide(STORAGE_RUNTIME_CONTROLLER_CAPABILITY, service);
    const resources = ctx.capability(RESOURCE_REGISTRY_CAPABILITY);
    const resourceId = "storage.status";
    resources.register<StorageRuntimeSnapshot, readonly string[]>({
      id: resourceId,
      scope: "global",
      key: () => [resourceId],
      load: async () => ({ status: service.status(), healthStatus: (service as StorageRuntimeController & { healthStatus?: () => import("@keymaster/contracts").StorageRuntimeStatus }).healthStatus?.(), catalogBucket: (service as StorageRuntimeController & { isCatalogBucket?: () => boolean }).isCatalogBucket?.() === true, hasCatalogBuckets: service.hasCatalogBuckets?.() === true, authorityRecovery: (service as StorageRuntimeController & { authorityRecovery?: () => import("@keymaster/contracts").CoordinatorAuthorityRecovery }).authorityRecovery?.(), summary: await service.getProviderSummary(), capabilities: service.getConditionalCapabilities() }),
      subscribe: (_args, _context, invalidate) => service.subscribe(invalidate),
      invalidation: "immediate"
    });
    const topbar = ctx.capability(TOPBAR_REGISTRY_CAPABILITY);
    const topbarId = "storage.bucket-manager";
    topbar.register({
      id: topbarId,
      label: { key: "storage.bucketManager.topbar", fallback: "Storage buckets" },
      component: StorageBucketManagerEntry,
      order: 80
    });
    return () => {
      // topbar/resource 注册均由当前 WebLoom Scope 拥有。身份切换会先撤销
      // Scope，再执行 teardown；此时手工 unregister 会因 Scope=stopping
      // 失败，并把本可重启的 Storage 插件错误推进 error-disabled。
      // scoped registry 会自动精确回收这两项，这里只释放领域服务。
      service.dispose();
    };
  }
} satisfies PluginManifest & { setup: PluginSetup };

const { setup: storagePlatformSetup, ...storagePlatformPlugin } = storagePlatformPluginDefinition;

export { storagePlatformPlugin, storagePlatformSetup };
