// Worker-safe Storage runtime exports. Keep this entrypoint free of the page
// manifest and React settings UI so it can be bundled into SharedWorker.
export { createStorageRuntimeController, StorageRuntimeControllerImpl } from "../runtime/storageController.js";
export { openMultipartUploadRepository, MULTIPART_REPOSITORY_NAME, MULTIPART_REPOSITORY_VERSION } from "../bootstrap/multipartUploadRepository.js";
export type { MultipartUploadRepository, StoredMultipartUploadRecord } from "../bootstrap/multipartUploadRepository.js";
export { StorageRuntimeError } from "../runtime/storageError.js";
export { browserStorageLocks, browserStorageLockMode } from "../runtime/browserLocks.js";
export { createS3BucketProvider } from "../bucket-providers/s3/s3BucketProvider.js";
export { createS3BucketObjectStore } from "../bucket-providers/s3/s3BucketObjectStore.js";
export { createKeyValueStore } from "../kv-engine/partitionedKvEngine.js";
export type { KeyValueStoreOptions, KeyValueStoreMaintenance, KeyValueGarbageCollectionResult } from "../kv-engine/partitionedKvEngine.js";
export { createFixedCasSnapshotStore } from "../snapshot/fixedCasSnapshotStore.js";
export { createOwnerLifecycleGuardedProvider, createPlatformRootStore, validatePublishedPlatformBucketSchema } from "../storage-access/platform-root/platformRootStore.js";
export { createStorageBindingAuthority } from "./storageBindingAuthority.js";
export type { StorageBindingAuthorityOptions } from "./storageBindingAuthority.js";
export { createOwnerAppStore } from "../storage-access/owner-app/ownerAppStore.js";
export { readStorageBootstrap } from "../bootstrap/storageProfileRepository.js";
export { createDeviceBootstrapRepository, readDeviceBootstrap, writeDeviceBootstrap, clearDeviceBootstrap, defaultDeviceBootstrapStorage, DEVICE_BOOTSTRAP_KEY, DEVICE_BOOTSTRAP_LOCK } from "../bootstrap/deviceBootstrapRepository.js";
export type { DeviceBootstrapRepository, DeviceBootstrapRepositoryOptions, DeviceBootstrapStorage, DeviceBootstrapLocks } from "../bootstrap/deviceBootstrapRepository.js";
export { discoverRemoteStorageRoot, validateRemoteRootManifest, sealRemoteRootManifest, verifyRemoteRootManifest, encodeRemoteRootManifest, decodeRemoteRootManifest, remoteRootManifestFingerprint, physicalLocationFingerprint, remoteInitializationTransactionPath, remoteInitializationStagingPath, createHmacRemoteRootAuthenticator, deriveRemoteRootAuthenticator } from "../bootstrap/remoteRootProtocol.js";
export type { RemoteRootAuthenticator, RemoteRootDiscoveryResult, RemoteRootObject, RemoteStorageRootManifestInput } from "../bootstrap/remoteRootProtocol.js";
export { createRemoteStorage, connectExistingRemoteStorage } from "../bootstrap/remoteStorageLifecycle.js";
export type { RemoteStorageCreatePlan, RemoteStorageConnectPlan, RemoteStorageLifecycleSuccess, RemoteStorageCreatePhase, RemoteStorageConnectPhase } from "../bootstrap/remoteStorageLifecycle.js";
export { normalizeProviderConfig } from "../bucket-providers/s3/s3ClientFactory.js";
export { StorageBootstrapController } from "../bootstrap/storageBootstrapController.js";
export type { StorageBootstrapControllerOptions, StorageBootstrapResult } from "../bootstrap/storageBootstrapController.js";
export { StorageHealthController } from "../runtime/storageHealthController.js";
export type { StorageHealthSnapshot, StorageProbeOptions } from "../runtime/storageHealthController.js";
export { createLocalStorageBucketProvider } from "../bucket-providers/local/localStorageBucketProvider.js";
export type { LocalStorageLike, LocalStorageBridgeCandidateBucket, LocalStorageBridgeRequest, LocalStorageBridgeResponse } from "../bucket-providers/local/localStorageBucketProvider.js";
export { createStorageCatalogRepository, readStorageCatalog, writeStorageCatalog, clearStorageCatalog, validateStorageCatalog, sameStorageCatalogEntry, sameStorageCatalogDeviceProjection, STORAGE_CATALOG_LOCK } from "../bootstrap/storageCatalogRepository.js";
export { createBucketCryptoContext, deriveBucketCryptoContext, encryptBucketConfig, decryptBucketConfig, encryptBucketKey, decryptBucketKey, sealBucketDocument, verifyBucketDocument, parseBucketDocument, serializeBucketDocument } from "../hold/keymasterHoldAdapter.js";
export { createStorageHoldSnapshotRepository, createStorageHoldSnapshotReadOnlyRepository, STORAGE_HOLD_HEAD_PATH } from "../hold/storageHoldSnapshotRepository.js";
export { createStorageBucketManagementService } from "../hold/storageBucketManagement.js";
