import type { I18nPluginResources } from "@keymaster/contracts";
export const collectiblesResources: I18nPluginResources = {
  namespace: "collectibles",
  resources: {
    en: {
      "collectibles.route.list": "Collectibles",
      "collectibles.route.detail": "Collectible detail",
      "collectibles.menu.list": "Collectibles",
      "collectibles.redirect.missing": "Missing providerId/collectibleId parameter.",
      "collectibles.network.main": "Mainnet",
      "collectibles.network.test": "Testnet",
      "collectibles.observation.confirmed": "WOC confirmed",
      "collectibles.observation.unconfirmed": "WOC observed (unconfirmed)",
      "collectibles.page.eyebrow": "Collectibles",
      "collectibles.page.title": "Collectibles",
      "collectibles.page.lede.mainnet": "Browse individual collectibles by provider. Mainnet only is shown.",
      "collectibles.page.lede.testnet": "Browse individual collectibles by provider. Mainnet and testnet are shown separately.",
      "collectibles.page.scope.main": "Mainnet only",
      "collectibles.page.scope.dual": "Mainnet + testnet",
      "collectibles.page.mint": "Create collectible",
      "collectibles.page.stats": "Summary",
      "collectibles.page.stats.providers": "Providers",
      "collectibles.page.stats.items": "Items",
      "collectibles.page.stats.ready": "Ready",
      "collectibles.page.empty.providers.title": "No collectible providers",
      "collectibles.page.providers.title": "Providers",
      "collectibles.page.providers.desc": "Each provider keeps its own registry and status.",
      "collectibles.page.provider.empty": "No items yet.",
      "collectibles.status.ready": "Ready",
      "collectibles.status.syncing": "Syncing",
      "collectibles.status.stale": "Stale",
      "collectibles.status.failed": "Failed",
      "collectibles.status.unsupported": "Unsupported",
      "collectibles.detail.transfer": "Transfer"
    },
    "zh-CN": {
      "collectibles.route.list": "藏品",
      "collectibles.route.detail": "藏品详情",
      "collectibles.menu.list": "藏品",
      "collectibles.redirect.missing": "缺少 providerId/collectibleId 参数。",
      "collectibles.network.main": "主网",
      "collectibles.network.test": "测试网",
      "collectibles.observation.confirmed": "WOC 已确认",
      "collectibles.observation.unconfirmed": "WOC 已观察（未确认）",
      "collectibles.page.eyebrow": "藏品工作区",
      "collectibles.page.title": "藏品",
      "collectibles.page.lede.mainnet": "按 provider 浏览单件藏品。当前只显示主网。",
      "collectibles.page.lede.testnet": "按 provider 浏览单件藏品。主网和测试网会分开展示。",
      "collectibles.page.scope.main": "仅主网",
      "collectibles.page.scope.dual": "主网 + 测试网",
      "collectibles.page.mint": "创建藏品",
      "collectibles.page.stats": "汇总",
      "collectibles.page.stats.providers": "Provider",
      "collectibles.page.stats.items": "条目",
      "collectibles.page.stats.ready": "就绪",
      "collectibles.page.empty.providers.title": "暂无藏品 provider",
      "collectibles.page.providers.title": "Provider",
      "collectibles.page.providers.desc": "每个 provider 都维护自己的注册表和状态。",
      "collectibles.page.provider.empty": "暂无条目。",
      "collectibles.status.ready": "就绪",
      "collectibles.status.syncing": "同步中",
      "collectibles.status.stale": "已过期",
      "collectibles.status.failed": "失败",
      "collectibles.status.unsupported": "不支持",
      "collectibles.detail.transfer": "转移"
    }
  }
};

