// Forum 资源投影与 i18n。
//
// 投影只提供可重建的视图：配置列表、根验证状态、发布任务列表。索引页与正文
// 由页面自己按游标世代拉取，因此不注册成 ResourceDefinition —— 分页的状态机
// 需要页面持有世代与游标，注册成资源反而会丢掉这两样。

import type { I18nPluginResources } from "@keymaster/contracts";

export const forumResources: I18nPluginResources = {
  namespace: "forum",
  resources: {
    en: {
      "forum.page.title": "Forum",
      "forum.page.subtitle": "BSV8 Forum client",
      "forum.config.title": "Forum connections",
      "forum.config.add": "Add forum",
      "forum.config.label": "Label",
      "forum.config.forumTxid": "Genesis root txid",
      "forum.config.forumKey": "Forum service public key",
      "forum.config.network": "Network",
      "forum.config.endpoints": "Endpoints",
      "forum.config.verifyRoot": "Verify genesis root",
      "forum.config.verified": "Root verified",
      "forum.config.unverified": "Root not verified",
      "forum.config.networkMismatch": "Forum network differs from the wallet network",
      "forum.list.boards": "Boards",
      "forum.list.posts": "Posts",
      "forum.list.replies": "Replies",
      "forum.list.loadMore": "Load more",
      "forum.list.refresh": "Refresh",
      "forum.list.exhausted": "End of current view; new replies may appear later",
      "forum.list.stale": "Cached view — not current pricing truth",
      "forum.list.needsRefresh": "The server view kept changing. Refresh to continue.",
      "forum.node.initialPrice": "Initial reply price",
      "forum.node.confirmedPrice": "Confirmed reply price",
      "forum.node.effectivePrice": "Effective reply price",
      "forum.node.status": "Chain status",
      "forum.read.open": "Read",
      "forum.read.fetching": "Fetching content…",
      "forum.read.notFetched": "Content not fetched yet",
      "forum.read.unreachable": "Content source unreachable",
      "forum.read.verificationFailed": "Content failed verification",
      "forum.read.oversize": "Content exceeds the inline limit; open the file instead",
      "forum.read.offline": "Read from local copy",
      "forum.reply.title": "Reply",
      "forum.reply.submit": "Publish reply",
      "forum.reply.tipPrice": "Your future reply price",
      "forum.changetip.title": "Change reply price",
      "forum.changetip.submit": "Change price",
      "forum.publish.kind": "Operation",
      "forum.publish.fees": "Fee breakdown",
      "forum.publish.total": "Total",
      "forum.publish.confirm": "Confirm budget",
      "forum.publish.submit": "Broadcast",
      "forum.publish.broadcast": "Broadcast",
      "forum.publish.chain": "On-chain",
      "forum.publish.index": "Forum index",
      "forum.publish.changetipLimitation": "Whether this price change was accepted is not queryable",
      "forum.error.NODE_NOT_FOUND": "Node not found in this forum",
      "forum.error.INVALID_PARENT": "The parent node is not valid for this operation",
      "forum.error.SNAPSHOT_INVALIDATED": "The server view moved on",
      "forum.error.INVALID_CURSOR": "The paging cursor was rejected; reload the list",
    },
    "zh-CN": {
      "forum.page.title": "论坛",
      "forum.page.subtitle": "BSV8 Forum 客户端",
      "forum.config.title": "论坛连接",
      "forum.config.add": "添加论坛",
      "forum.config.label": "显示别名",
      "forum.config.forumTxid": "创世根 txid",
      "forum.config.forumKey": "论坛服务公钥",
      "forum.config.network": "网络",
      "forum.config.endpoints": "连接地址",
      "forum.config.verifyRoot": "验证创世根",
      "forum.config.verified": "根已验证",
      "forum.config.unverified": "根未验证",
      "forum.config.networkMismatch": "论坛网络与钱包网络不一致",
      "forum.list.boards": "板块",
      "forum.list.posts": "帖子",
      "forum.list.replies": "回复",
      "forum.list.loadMore": "加载更多",
      "forum.list.refresh": "刷新",
      "forum.list.exhausted": "当前视图已读完；之后仍可能出现新回复",
      "forum.list.stale": "缓存视图——不能作为当前报价真值",
      "forum.list.needsRefresh": "服务端视图持续变化，请刷新后继续",
      "forum.node.initialPrice": "初始回复价",
      "forum.node.confirmedPrice": "确认回复价",
      "forum.node.effectivePrice": "生效回复价",
      "forum.node.status": "链上状态",
      "forum.read.open": "阅读",
      "forum.read.fetching": "正在获取正文…",
      "forum.read.notFetched": "正文尚未获取",
      "forum.read.unreachable": "正文来源暂时不可达",
      "forum.read.verificationFailed": "正文校验失败",
      "forum.read.oversize": "正文超过内联上限，请改用文件入口",
      "forum.read.offline": "从本地副本阅读",
      "forum.reply.title": "回复",
      "forum.reply.submit": "发布回复",
      "forum.reply.tipPrice": "你的未来回复价",
      "forum.changetip.title": "修改回复价",
      "forum.changetip.submit": "修改价格",
      "forum.publish.kind": "操作类型",
      "forum.publish.fees": "费用明细",
      "forum.publish.total": "合计",
      "forum.publish.confirm": "确认预算",
      "forum.publish.submit": "广播",
      "forum.publish.broadcast": "广播",
      "forum.publish.chain": "链上观测",
      "forum.publish.index": "Forum 索引",
      "forum.publish.changetipLimitation": "当前接口无法查询该改价事件是否被接受",
      "forum.error.NODE_NOT_FOUND": "该论坛中没有这个节点",
      "forum.error.INVALID_PARENT": "父节点不适合这个操作",
      "forum.error.SNAPSHOT_INVALIDATED": "服务端视图已经变化",
      "forum.error.INVALID_CURSOR": "分页游标已被拒绝，请重新读取列表",
    },
  },
};