import type { I18nPluginResources } from "@keymaster/contracts";
export const assetsResources: I18nPluginResources = {
  namespace: "assets",
  resources: {
    en: {
      "assets.domain.label": "Wallet",
      "assets.route.list": "Asset overview",
      "assets.route.detail": "Asset detail",
      "assets.menu.list": "Asset overview",
      "assets.home.overview": "Asset overview",
      "assets.redirect.missing": "Missing providerId/assetId parameter.",
      "assets.context.noKey": "No key",
      "assets.context.unnamed": "Unnamed",
      "assets.network.main": "Mainnet",
      "assets.network.test": "Testnet",
      "assets.observation.confirmed": "WOC confirmed",
      "assets.observation.unconfirmed": "WOC observed (unconfirmed)",
      "assets.page.eyebrow": "Asset overview",
      "assets.page.title": "Assets",
      "assets.page.lede.mainnet": "View coins, tokens, and sync status aggregated by provider for your current key. Mainnet only is shown.",
      "assets.page.lede.testnet": "View coins, tokens, and sync status aggregated by provider for your current key. Mainnet and testnet are shown separately.",
      "assets.page.scope.main": "Mainnet only",
      "assets.page.scope.dual": "Mainnet + testnet",
      "assets.page.refresh": "Refresh",
      "assets.page.stats": "Summary",
      "assets.page.stats.assets": "Assets",
      "assets.page.stats.tokens": "Tokens",
      "assets.page.stats.ready": "Ready",
      "assets.page.empty.providers.title": "No asset providers",
      "assets.page.assets.desc": "Coins and provider-specific assets.",
      "assets.page.provider.empty": "No items yet.",
      "assets.page.tokens.title": "Tokens",
      "assets.page.tokens.desc": "BSV-21 and other token providers.",
      "assets.status.ready": "Ready",
      "assets.status.syncing": "Syncing",
      "assets.status.stale": "Stale",
      "assets.status.failed": "Failed",
      "assets.status.unsupported": "Unsupported",
      "assets.status.unavailable": "Wallet is locked or asset services are temporarily unavailable; unlock to restore.",
      "assets.balance.unknown": "Unknown"
    },
    "zh-CN": {
      "assets.domain.label": "钱包",
      "assets.route.list": "资产总览",
      "assets.route.detail": "资产详情",
      "assets.menu.list": "资产总览",
      "assets.home.overview": "资产总览",
      "assets.redirect.missing": "缺少 providerId/assetId 参数。",
      "assets.context.noKey": "无 key",
      "assets.context.unnamed": "未命名",
      "assets.network.main": "主网",
      "assets.network.test": "测试网",
      "assets.observation.confirmed": "WOC 已确认",
      "assets.observation.unconfirmed": "WOC 已观察（未确认）",
      "assets.page.eyebrow": "资产工作区",
      "assets.page.title": "资产",
      "assets.page.lede.mainnet": "按 provider 聚合展示当前 key 下的 coin、token 与同步状态。当前只显示主网。",
      "assets.page.lede.testnet": "按 provider 聚合展示当前 key 下的 coin、token 与同步状态。主网和测试网会分开展示。",
      "assets.page.scope.main": "仅主网",
      "assets.page.scope.dual": "主网 + 测试网",
      "assets.page.refresh": "刷新",
      "assets.page.stats": "汇总",
      "assets.page.stats.assets": "资产",
      "assets.page.stats.tokens": "代币",
      "assets.page.stats.ready": "就绪",
      "assets.page.empty.providers.title": "暂无资产 provider",
      "assets.page.assets.desc": "Coin 与各 provider 提供的资产。",
      "assets.page.provider.empty": "暂无条目。",
      "assets.page.tokens.title": "代币",
      "assets.page.tokens.desc": "BSV-21 及其他代币 provider。",
      "assets.status.ready": "就绪",
      "assets.status.syncing": "同步中",
      "assets.status.stale": "已过期",
      "assets.status.failed": "失败",
      "assets.status.unsupported": "不支持",
      "assets.status.unavailable": "钱包已锁定或资产服务暂不可用；解锁后会自动恢复。",
      "assets.balance.unknown": "未知"
    }
  }
};

