import type { I18nPluginResources } from "@keymaster/contracts";
export const settingsResources: I18nPluginResources = {
  // 这批 key 的调用方长期使用 `t("settings.*") / t("pluginManager.*")`，
  // 并不把 `settings` 当 namespace 前缀来传。
  // 因此资源必须挂在 common namespace，才能让这些 flat key 直接命中。
  namespace: "common",
  resources: {
    en: {
      "settings.route.plugins": "Plugins",
      "settings.business.domain": "Settings",
      "settings.business.plugins": "Plugin settings",
      "settings.systemStatus.title": "Broadcast gateway",
      "settings.systemStatus.description": "Manage broadcast gateway suppliers and service status.",
      "settings.systemStatus.empty": "No broadcast gateway modules are available.",
      "settings.menu.plugins": "Plugins",
      "settings.crumb.settings": "Settings",
      "settings.crumb.plugins": "Plugins",
      "settings.language.title": "Language",
      "settings.language.description": "Choose display language. Affects all UI text; switch is instant.",
      "settings.language.option.en": "English",
      "settings.language.option.zh-CN": "Simplified Chinese",
      // 硬切换 001：插件管理页
      "pluginManager.title": "Plugin dependencies",
      "pluginManager.graph.search": "Search plugins",
      "pluginManager.graph.zoomOut": "Zoom out",
      "pluginManager.graph.showPage": "Show Page dependencies",
      "pluginManager.graph.showVault": "Show Vault dependencies",
      "pluginManager.graph.zoomIn": "Zoom in",
      "pluginManager.graph.legend": "Arrow: caller → provider · Dashed: optional · Select a node for function details",
      "pluginManager.graph.plugins": "plugins",
      "pluginManager.graph.links": "dependency links",
      "pluginManager.graph.empty": "No matching dependencies.",
      "pluginManager.graph.canvas": "Plugin dependency graph",
      "pluginManager.graph.details": "Function dependencies",
      "pluginManager.graph.close": "Close function dependencies",
      "pluginManager.graph.staticNote": "Extracted from source calls and declared service contracts. These are static dependencies, not live call counts. Window and Worker providers are matched separately.",
      "pluginManager.graph.direction": "Dependency direction",
      "pluginManager.graph.outgoing": "Functions called",
      "pluginManager.graph.incoming": "Called by",
      "pluginManager.graph.functionSearch": "Search functions, services or source files",
      "pluginManager.graph.callSites": "source call sites",
      "pluginManager.graph.noCalls": "No statically resolved cross-plugin method calls in this direction. Declared dependencies are listed above; injected and dynamic calls may not be resolved.",
      "pluginManager.description":
        "Explore plugin dependencies. Select a plugin to inspect function calls.",
      "pluginManager.error": "Error",
      "pluginManager.meta.id": "Id",
      "pluginManager.meta.provides": "Provides",
      "pluginManager.meta.depends": "Depends on",
      "pluginManager.meta.reverse": "Used by",
      "pluginManager.meta.none": "—",
      "pluginManager.meta.blockers": "Blocking dependents",
      "pluginManager.meta.blockersHint":
        "These dependents will stop automatically and keep their enable intent.",
      "pluginManager.meta.cascade": "Will stop dependents",
      "pluginManager.meta.cascadeHint":
        "Disabling this plugin will stop the listed dependents; their enable intent is preserved.",
      "pluginManager.action.retry": "Retry",
      "pluginManager.action.retrying": "Recovering…",
      "pluginManager.action.enable": "Enable",
      "pluginManager.action.disable": "Disable",
      "pluginManager.action.cannotDisable": "Cannot disable",
      "pluginManager.group.core": "Core",
      "pluginManager.group.platform": "Platform",
      "pluginManager.group.business": "Business",
      "pluginManager.group.import": "Import",
      "pluginManager.group.experimental": "Experimental",
      "pluginManager.group.other": "Other",
      "pluginManager.dep.title": "Dependencies",
      "pluginManager.dep.dependsOn": "Depends on",
      "pluginManager.dep.usedBy": "Used by",
      "pluginManager.dep.missing": "Missing dependencies: {{list}}",
      "pluginManager.details": "Details",
      "pluginManager.details.hide": "Hide details",
      "pluginManager.state.enabled": "Enabled",
      "pluginManager.state.starting": "Starting",
      "pluginManager.state.stopping": "Stopping",
      "pluginManager.state.disabled": "Disabled",
      "pluginManager.state.blocked": "Blocked (missing dependency)",
      "pluginManager.state.errorDisabled": "Error-disabled",
      "pluginManager.state.cleanupPending": "Cleanup pending",
      "pluginManager.state.intentPending": "Enable intent is pending runtime state",
      "pluginManager.state.registered": "Registered",
    },
    "zh-CN": {
      "settings.route.plugins": "插件",
      "settings.business.domain": "设置",
      "settings.business.plugins": "插件设置",
      "settings.systemStatus.title": "广播网关",
      "settings.systemStatus.description": "管理广播网关供应商与服务状态。",
      "settings.systemStatus.empty": "当前没有可用的广播网关模块。",
      "settings.menu.plugins": "插件",
      "settings.crumb.settings": "设置",
      "settings.crumb.plugins": "插件",
      "settings.language.title": "语言",
      "settings.language.description": "选择界面显示语言，影响所有 UI 文案；切换立即生效。",
      "settings.language.option.en": "English",
      "settings.language.option.zh-CN": "简体中文",
      // 硬切换 001：插件管理页
      "pluginManager.title": "插件依赖关系",
      "pluginManager.graph.search": "搜索插件",
      "pluginManager.graph.zoomOut": "缩小",
      "pluginManager.graph.showPage": "显示 Page 依赖",
      "pluginManager.graph.showVault": "显示 Vault 依赖",
      "pluginManager.graph.zoomIn": "放大",
      "pluginManager.graph.legend": "箭头：调用方 → 提供方 · 虚线：可选依赖 · 点击节点查看函数详情",
      "pluginManager.graph.plugins": "个插件",
      "pluginManager.graph.links": "条依赖关系",
      "pluginManager.graph.empty": "没有匹配的依赖。",
      "pluginManager.graph.canvas": "插件依赖图",
      "pluginManager.graph.details": "函数依赖",
      "pluginManager.graph.close": "关闭函数依赖",
      "pluginManager.graph.staticNote": "依据源码调用点和服务契约生成静态依赖，不表示实时调用次数；Window 与 Worker 提供方分别匹配。",
      "pluginManager.graph.direction": "依赖方向",
      "pluginManager.graph.outgoing": "调用的函数",
      "pluginManager.graph.incoming": "被哪些函数调用",
      "pluginManager.graph.functionSearch": "搜索函数、服务或源码文件",
      "pluginManager.graph.callSites": "个源码调用点",
      "pluginManager.graph.noCalls": "此方向没有静态解析到的跨插件方法调用。声明的依赖已列在上方；注入和动态调用可能无法解析。",
      "pluginManager.description": "查看插件之间的依赖；点击插件查看函数调用关系。",
      "pluginManager.error": "错误",
      "pluginManager.meta.id": "Id",
      "pluginManager.meta.provides": "提供",
      "pluginManager.meta.depends": "依赖",
      "pluginManager.meta.reverse": "被谁依赖",
      "pluginManager.meta.none": "—",
      "pluginManager.meta.blockers": "阻塞的反向依赖",
      "pluginManager.meta.blockersHint": "依赖变化会触发实例撤销与恢复。",
      "pluginManager.meta.cascade": "将自动停止依赖插件",
      "pluginManager.meta.cascadeHint": "禁用本插件会自动停止列表中的依赖插件，但不会改写它们的启用意图。",
      "pluginManager.action.retry": "重试",
      "pluginManager.action.retrying": "恢复中…",
      "pluginManager.action.enable": "启用",
      "pluginManager.action.disable": "禁用",
      "pluginManager.action.cannotDisable": "不可禁用",
      "pluginManager.group.core": "核心",
      "pluginManager.group.platform": "平台",
      "pluginManager.group.business": "业务",
      "pluginManager.group.import": "导入",
      "pluginManager.group.experimental": "实验",
      "pluginManager.group.other": "其它",
      "pluginManager.dep.title": "依赖",
      "pluginManager.dep.dependsOn": "依赖",
      "pluginManager.dep.usedBy": "被谁依赖",
      "pluginManager.dep.missing": "缺少依赖：{{list}}",
      "pluginManager.details": "详情",
      "pluginManager.details.hide": "收起详情",
      "pluginManager.state.enabled": "已启用",
      "pluginManager.state.starting": "启动中",
      "pluginManager.state.stopping": "停止中",
      "pluginManager.state.disabled": "已禁用",
      "pluginManager.state.blocked": "被阻塞（依赖缺失）",
      "pluginManager.state.errorDisabled": "错误已禁用",
      "pluginManager.state.cleanupPending": "清理未完成",
      "pluginManager.state.intentPending": "启用意图正在等待运行状态收敛",
      "pluginManager.state.registered": "已注册",
    }
  }
};
