import type { I18nPluginResources } from "@keymaster/contracts";
export const transferResources: I18nPluginResources = {
  namespace: "p2pkh",
  resources: {
    en: {
      "p2pkh.transferPage.route.title": "Transfer",
      "p2pkh.transferPage.menu.title": "Transfer",
      "p2pkh.transferPage.crumb.wallet": "Wallets",
      "p2pkh.transferPage.crumb.title": "Transfer",
      "p2pkh.transferPage.action.toContact": "Transfer",
      "p2pkh.transferPage.observation.confirmed": "WOC confirmed",
      "p2pkh.transferPage.observation.unconfirmed": "WOC observed (unconfirmed)",
      "p2pkh.transferPage.page.desc.default": "Choose a recipient address, enter the amount and fee rate, then verify the read-only transfer details before submitting.",
      "p2pkh.transferPage.page.recipient.title": "Recipient",
      "p2pkh.transferPage.page.recipient.hint": "Search a contact or paste a compressed public key or P2PKH address.",
      "p2pkh.transferPage.page.recipient.contacts": "From contacts",
      "p2pkh.transferPage.page.recipient.manual": "Manual input",
      "p2pkh.transferPage.page.recipient.publicKey": "Recipient public key",
      "p2pkh.transferPage.page.recipient.change": "Change recipient",
      "p2pkh.transferPage.page.recipient.placeholder": "Select a contact",
      "p2pkh.transferPage.page.recipient.inputPlaceholder": "Paste public key, address, or search a contact",
      "p2pkh.transferPage.page.recipient.address": "Recipient address",
      "p2pkh.transferPage.page.recipient.copy": "Copy address",
      "p2pkh.transferPage.page.recipient.copied": "Copied",
      "p2pkh.transferPage.page.recipient.network": "Network",
      "p2pkh.transferPage.page.recipient.mainnet": "Mainnet",
      "p2pkh.transferPage.page.recipient.testnet": "Testnet",
      "p2pkh.transferPage.page.recipient.source.contact": "Contact public-key derivation",
      "p2pkh.transferPage.page.recipient.source.resolved": "Address matched contact",
      "p2pkh.transferPage.page.recipient.source.manualPublicKey": "Manual public key",
      "p2pkh.transferPage.page.recipient.source.manualAddress": "Manual address",
      "p2pkh.transferPage.page.recipient.unknownAddress": "Unknown address",
      "p2pkh.transferPage.page.recipient.noCodec": "The P2PKH address capability is unavailable; address lookup is disabled.",
      "p2pkh.transferPage.page.recipient.searchHint": "Other text is searched in local contacts.",
      "p2pkh.transferPage.page.recipient.searchEmpty": "No matching local contact.",
      "p2pkh.transferPage.page.recipient.invalidPublicKey": "Public key must be a compressed 33-byte hex key.",
      "p2pkh.transferPage.page.recipient.invalidAddress": "This is not a valid P2PKH address. Use the corresponding asset transfer entry.",
      "p2pkh.transferPage.page.recipient.testnetDisabled": "Testnet is not enabled. Enable testnet in settings first.",
      "p2pkh.transferPage.page.recipient.conflict": "The public key and address do not match; transfer is blocked.",
      "p2pkh.transferPage.page.recipient.networkChanged": "Address updated; verify again before submitting.",
      "p2pkh.transferPage.page.empty.noKey.title": "No key yet",
      "p2pkh.transferPage.page.empty.noKey.desc": "Import or create a key before starting a transfer.",
      "p2pkh.transferPage.page.empty.noProvider.title": "No provider",
      "p2pkh.transferPage.page.empty.picker": "No ordinary BSV (P2PKH) transfer is currently available.",
      "p2pkh.transferPage.page.invalidRecipient": "The recipient parameters are invalid.",
      "p2pkh.transferPage.page.noRecipientProvider": "No ordinary BSV transfer is available for this network.",
      "p2pkh.transferPage.page.clearRecipient": "Clear recipient"
    },
    "zh-CN": {
      "p2pkh.transferPage.route.title": "转账",
      "p2pkh.transferPage.menu.title": "转账",
      "p2pkh.transferPage.crumb.wallet": "钱包",
      "p2pkh.transferPage.crumb.title": "转账",
      "p2pkh.transferPage.action.toContact": "转账",
      "p2pkh.transferPage.observation.confirmed": "WOC 已确认",
      "p2pkh.transferPage.observation.unconfirmed": "WOC 已观察（未确认）",
      "p2pkh.transferPage.page.desc.default": "选择收款地址，填写金额与矿工费率，再核对只读转账信息后提交。",
      "p2pkh.transferPage.page.recipient.title": "收款方",
      "p2pkh.transferPage.page.recipient.hint": "搜索联系人，或粘贴压缩公钥、P2PKH 地址。",
      "p2pkh.transferPage.page.recipient.contacts": "从通讯录选择",
      "p2pkh.transferPage.page.recipient.manual": "手工输入",
      "p2pkh.transferPage.page.recipient.publicKey": "收款人公钥",
      "p2pkh.transferPage.page.recipient.change": "更换收款方",
      "p2pkh.transferPage.page.recipient.placeholder": "选择联系人",
      "p2pkh.transferPage.page.recipient.inputPlaceholder": "粘贴公钥、地址，或搜索联系人",
      "p2pkh.transferPage.page.recipient.address": "收款地址",
      "p2pkh.transferPage.page.recipient.copy": "复制地址",
      "p2pkh.transferPage.page.recipient.copied": "已复制",
      "p2pkh.transferPage.page.recipient.network": "网络",
      "p2pkh.transferPage.page.recipient.mainnet": "主网",
      "p2pkh.transferPage.page.recipient.testnet": "testnet",
      "p2pkh.transferPage.page.recipient.source.contact": "联系人公钥派生",
      "p2pkh.transferPage.page.recipient.source.resolved": "地址命中联系人",
      "p2pkh.transferPage.page.recipient.source.manualPublicKey": "手工公钥",
      "p2pkh.transferPage.page.recipient.source.manualAddress": "手工地址",
      "p2pkh.transferPage.page.recipient.unknownAddress": "陌生地址",
      "p2pkh.transferPage.page.recipient.noCodec": "P2PKH 地址能力不可用，地址反查已关闭。",
      "p2pkh.transferPage.page.recipient.searchHint": "其他文本会在本地通讯录中搜索。",
      "p2pkh.transferPage.page.recipient.searchEmpty": "没有匹配的本地联系人。",
      "p2pkh.transferPage.page.recipient.invalidPublicKey": "公钥必须是压缩格式的 33 字节 hex 公钥。",
      "p2pkh.transferPage.page.recipient.invalidAddress": "这不是有效的 P2PKH 地址，请从对应资产入口转账。",
      "p2pkh.transferPage.page.recipient.testnetDisabled": "未启用 testnet，请在设置中开启。",
      "p2pkh.transferPage.page.recipient.conflict": "公钥与地址不一致，已阻断转账。",
      "p2pkh.transferPage.page.recipient.networkChanged": "地址已更新，请重新核对。",
      "p2pkh.transferPage.page.empty.noKey.title": "还没有 key",
      "p2pkh.transferPage.page.empty.noKey.desc": "导入或创建一个 key 后再开始转账。",
      "p2pkh.transferPage.page.empty.noProvider.title": "没有 provider",
      "p2pkh.transferPage.page.empty.picker": "当前没有可用的普通 BSV（P2PKH）转账。",
      "p2pkh.transferPage.page.invalidRecipient": "收款方参数无效。",
      "p2pkh.transferPage.page.noRecipientProvider": "当前网络没有可用的普通 BSV 转账。",
      "p2pkh.transferPage.page.clearRecipient": "清除收款方"
    }
  }
};

